# Generated by Django 3.2 on 2021-04-17 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='posters/')),
                ('description', models.CharField(max_length=100)),
                ('url', models.SlugField(max_length=100)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='cars.car')),
            ],
        ),
    ]
